version: '3.7'

services:
  # Backend
  smart-brain-api:
    container_name: backend
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    ports:
      - "3001:3001"
    environment:
      POSTGRES_URI: postgres://sally:secretpass@postgres:5432/smart-brain
      REDIS_URI: redis://redis:6379
      JWT_SECRET: JWT-SECRET
    # volumes:
    #   - ./:/usr/src/smart-brain-api

  # Postgres
  postgres:
    container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: smart-brain
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"